POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVyaWtwZXRlcmkiLCJpZCI6IjY0NzM1MTIwYzI0ZGU5ZmI3MzQxNTJkMyIsImlhdCI6MTY4NTI3OTA0Mn0.JnFlFAnW-Vv0Sjf4Yy58bG-ESLtjcXq_xS1FSROCVOA

{
  "title": "uusi blogi",
  "author": "testi mies",
  "url": "https://www.example.com",
  "likes": 20,
  "userId": "64735120c24de9fb734152d3"

}


