POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphbnRza3VsaSIsImlkIjoiNjQ3YzlmNDg1NjUzOTg0N2ZmZGE5N2RmIiwiaWF0IjoxNjg1ODkyNzExfQ.XKedIifvlZ4RY_yfQOwTYPTpQmCivfkPJHOty-0fVOQ

{
  "title": "uusi blogi",
  "author": "testi",
  "url": "https://www.example.com",
  "likes": 20,
  "userId": "647c9f4856539847ffda97df"

}


